# Generated by Django 4.2.1 on 2023-06-04 20:12

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BaseUserModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="E-mail"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(max_length=12, verbose_name="Número de telefone"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data de Criação"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Data de Atualização"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommissionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day",
                    models.CharField(
                        choices=[
                            ("mon", "Segunda-feira"),
                            ("tue", "Terça-feira"),
                            ("wed", "Quarta-feira"),
                            ("thu", "Quinta-feira"),
                            ("fri", "Sexta-feira"),
                            ("sat", "Sábado"),
                            ("sun", "Domingo"),
                        ],
                        max_length=3,
                        unique=True,
                        verbose_name="Dia da Semana",
                    ),
                ),
                (
                    "min_commission_percentage",
                    models.IntegerField(verbose_name="Mínimo de Comissão"),
                ),
                (
                    "max_commission_percentage",
                    models.IntegerField(verbose_name="Máximo de Comissão"),
                ),
            ],
            options={
                "verbose_name": "Configurações da Comissão",
                "verbose_name_plural": "Configurações de Comissões",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Código do Produto"
                    ),
                ),
                (
                    "unitary_value",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        verbose_name="Valor Unitário",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descrição"),
                ),
                (
                    "commission_percentage",
                    models.IntegerField(verbose_name="Porcentagem de Comissão"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "baseusermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="provider.baseusermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente",
            },
            bases=("provider.baseusermodel",),
        ),
        migrations.CreateModel(
            name="Seller",
            fields=[
                (
                    "baseusermodel_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="provider.baseusermodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vendedor",
                "verbose_name_plural": "Vendedores",
            },
            bases=("provider.baseusermodel",),
        ),
    ]
