# Generated by Django 4.2.1 on 2023-06-04 23:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("provider", "0002_sale"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Produto"},
        ),
        migrations.AlterModelOptions(
            name="sale",
            options={"verbose_name": "Venda"},
        ),
        migrations.RenameField(
            model_name="sale",
            old_name="products",
            new_name="product",
        ),
    ]
